Import Jack Server '1.3'
Adapt to use server C.
Use Jack Brest by default.

jack-3.2.ALPHA.jar (C): 183700 230200ee3d09316ae71dba572c468c254c41b50f

Server version 1.3-a1: 209101 f0b690ecfdff1e511226dbfafaad8d27e81bb2da
jack-admin version 1.3-a3: 0d1021b79d4e59625134713911902e46c15a8998

Import Jack and Jill Brest 1.1-mr4
Jack version: 175600 dd2921b960a2553324c18ffecdcba1a8f368cc5e
Jill version: 175600 ea35bba48c1197e2ed9d21c0f33cadb2b6c27994

(cherry picked from commit 0fe933e54c44550727b7fbb8e041735eeb8a033a)
(cherry picked from commit 1b4e90524552651cbddb5930639a5691dca1a5dd)
(cherry picked from commit 6577bfe1406d9d002cfdf6405b9dbe5c79b48f17)
(cherry picked from commit 2b3b78a13e70add7cbc7639f7936d1d52f2689b3)
(cherry picked from commit c97096c82ba0810c8b35b3f021e6bee9a184a6b0)
(cherry picked from commit 7aa0ad0229a55b21a2352196268fa242872ac58a)
(cherry picked from commit eaba83f5abeeb079cf0deb19ed51a39641f6d26e)
(cherry picked from commit c8ba8135347ba4796400ef152b11cd78fb5f7b6f)
(cherry picked from commit 2070144fd0bc9207f21b4a97ce1568c8f36d399a)
(cherry picked from commit 5ea6d095cc111ce11141b923457d2c119e294934)
(cherry picked from commit e195f859a277808e2e44ac90e06f1e09874a1573)
(cherry picked from commit ca9f3ec94ce67d8f91995c2c4b01f73e2f9b6178)
(cherry picked from commit 06f3fcbf43e4c85cddca08139e9fb1fb0a4b08b4)

Change-Id: I3fffae7f0a96a79e222d7d1fd72d92b26707292e

diff --git a/tools/jack-admin b/tools/jack-admin
--- a/tools/jack-admin
+++ b/tools/jack-admin
@@ -14,156 +14,540 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #
-# Version: 1.1-mr2
+# Version: 1.3-a3
 #
 set -o nounset
+BASE_UMASK=$(umask)
 umask 077
 
 #
 # Settings
 #
-LOCAL_SETTING="$HOME/.jack"
+JACK_HOME="${JACK_HOME:=$HOME/.jack-server}"
+CLIENT_SETTING="${CLIENT_SETTING:=$HOME/.jack-settings}"
 TMPDIR=${TMPDIR:=/tmp}
-SERVER_DIR=$TMPDIR/jack-$USER
+JACK_SERVER_VM_ARGUMENTS="${JACK_SERVER_VM_ARGUMENTS:=-Dfile.encoding=UTF-8 -XX:+TieredCompilation}"
+
+LAUNCHER_JAR="$JACK_HOME/launcher.jar"
+LAUNCHER_NAME=com.android.jack.launcher.ServerLauncher
+CURRENT_CHARSET=$(locale charmap)
+JACK_LOGS_DIR="$JACK_HOME"/logs
+JACK_OUT_ERR="$JACK_LOGS_DIR"/outputs.txt
 
 #
-# Load local settings
+# Load client settings
 #
-source "$LOCAL_SETTING" 2>/dev/null
-
-#
-# Create or update local settings if needed
-#
-if [[ ! -f "$LOCAL_SETTING" || $SETTING_VERSION -lt 2 ]]; then
-  echo "Writing local settings in" $LOCAL_SETTING
-  cat >"$LOCAL_SETTING.$$" <<-EOT
-	# Server settings
-	SERVER=${SERVER:=true}
-	SERVER_PORT_SERVICE=${SERVER_PORT_SERVICE:=8072}
-	SERVER_PORT_ADMIN=${SERVER_PORT_ADMIN:=8073}
-	SERVER_COUNT=${SERVER_COUNT:=1}
-	SERVER_NB_COMPILE=${SERVER_NB_COMPILE:=4}
-	SERVER_TIMEOUT=${SERVER_TIMEOUT:=60}
-	SERVER_LOG=\${SERVER_LOG:=\$SERVER_DIR/jack-\$SERVER_PORT_SERVICE.log}
-	JACK_VM_COMMAND=\${JACK_VM_COMMAND:=java}
-	# Internal, do not touch
-	SETTING_VERSION=2
-EOT
-  ln -f "$LOCAL_SETTING.$$" "$LOCAL_SETTING"
-  rm "$LOCAL_SETTING.$$"
-  source "$LOCAL_SETTING"
+if [ -f "$CLIENT_SETTING" ]; then
+  source "$CLIENT_SETTING"
 fi
 
 #
-# Static setting
+# Create or update client settings if needed
 #
-mkdir "$SERVER_DIR" 2>/dev/null
+if [[ ! -f "$CLIENT_SETTING" || $SETTING_VERSION -lt 4 ]]; then
+  echo "Writing client settings in" $CLIENT_SETTING
+  cat >"$CLIENT_SETTING.$$" <<-EOT
+	# Server settings
+	SERVER_HOST=${SERVER_HOST:=127.0.0.1}
+	SERVER_PORT_SERVICE=${SERVER_PORT_SERVICE:=8076}
+	SERVER_PORT_ADMIN=${SERVER_PORT_ADMIN:=8077}
+
+	# Internal, do not touch
+	SETTING_VERSION=4
+EOT
+  ln -f "$CLIENT_SETTING.$$" "$CLIENT_SETTING"
+  rm "$CLIENT_SETTING.$$"
+  source "$CLIENT_SETTING"
+fi
+
+usage () {
+  echo "Usage : $0 [ install-server <launcher.jar> <server.jar> | uninstall-server | list <program> | update <program> <program.jar> | start-server | stop-server | kill-server | list-server | server-stat | server-log | server-gc | cleanup-server]"
+}
+
+abort () { exit 255; }
+
+#
+# $1: curl command status
+# $2: HTTP status
+#
+handleHttpErrors() {
+  if [ $1 -eq 0 ]; then
+    # No problem, let's go
+    return 0;
+  elif [ $1 -eq 7 ]; then
+    echo "No Jack server running. Try 'jack-admin start-server'" >&2
+    abort
+  elif [ $1 -eq 35 ]; then
+    echo "SSL error when connecting to the Jack server" >&2
+    abort
+  elif [ $1 -eq 58 ]; then
+    echo "Failed to contact Jack server: Problem reading ${JACK_HOME}/client.pem" >&2
+    abort
+  elif [ $1 -eq 60 ]; then
+    echo "Failed to authenticate Jack server certificate" >&2
+    abort
+   elif [ $1 -eq 77 ]; then
+    echo "Failed to contact Jack server: Problem reading ${JACK_HOME}/server.pem" >&2
+    abort
+  elif  [ $1 -eq 22 ]; then
+    # Http code not OK, let's decode and abort
+    if [ $2 -eq 400 ]; then
+      # 400: Bad request
+      echo "Bad request, see Jack server log" >&2
+      abort
+    else
+      # Other
+      echo "Internal unknown error ($2), try other ports or see Jack server log" >&2
+      abort
+    fi
+  else
+    # In case of partial, timeout, empty response, network error, let's retry
+    if [ $RETRY_SESSION -eq 0 ]; then
+      echo "Communication error with Jack server $1" >&2
+      abort
+    else
+      let RETRY_SESSION=RETRY_SESSION-1
+      return 1;
+    fi
+  fi
+}
+
+checkCurlVersion () {
+  curl --version | grep -q "SecureTransport"
+  if [ "$?" -eq 0 ]; then
+    echo "Unsupported curl, please use a curl not based on SecureTransport" >&2
+    abort
+  fi
+}
+
+#
+# $1: program name
+# $2: jar of the program
+#
+updateProgram () {
+  RETRY_SESSION=3
+  DONE=1
+  while [ "$DONE" -ne 0 ]; do
+    HTTP_CODE=$(curl -f \
+         --cert "${JACK_HOME}/client.pem" \
+         --cacert "${JACK_HOME}/server.pem" \
+         --output >(cat >/dev/null) \
+         --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
+         -X PUT \
+         -F "jar=@$2;type=application/octet-stream" \
+         -F "force=$FORCE_INSTALLATION;type=text/plain;charset=$CURRENT_CHARSET" \
+         --noproxy ${SERVER_HOST} \
+         https://${SERVER_HOST}:$SERVER_PORT_ADMIN/$1 \
+         )
+    handleHttpErrors $? $HTTP_CODE
+    DONE=$?
+  done
+
+
+  if [ "$1" == server ]; then
+    echo "Server updated, waiting for restart"
+    waitServerStarted
+  fi
+}
+
+isServerRunning () {
+  RETRY_SESSION=3
+  DONE=1
+  while [ "$DONE" -ne 0 ]; do
+    HTTP_CODE=$(curl -f \
+         --cert "${JACK_HOME}/client.pem" \
+         --cacert "${JACK_HOME}/server.pem" \
+         --output >(cat >/dev/null) \
+         --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
+         -X GET \
+         -H "Accept: text/plain;charset=$CURRENT_CHARSET" \
+         --noproxy ${SERVER_HOST} \
+         https://${SERVER_HOST}:$SERVER_PORT_ADMIN/server \
+         )
+    CURL_CODE=$?
+    if [ $CURL_CODE -eq 0 ]; then
+      # No problem, let's go
+      return 0;
+    elif [ $CURL_CODE -eq 7 ]; then
+      return 1
+    else
+      # In case of partial, timeout, empty response, network error, let's retry
+      if [ $RETRY_SESSION -eq 0 ]; then
+        echo "Communication error with Jack server $CURL_CODE, try other ports or see Jack server log"  >&2
+        abort
+      else
+        let RETRY_SESSION=RETRY_SESSION-1
+      fi
+    fi
+  done
+}
+
+waitServerStarted () {
+  RETRY_CONNECT=30
+  DONE=1
+  while [ "$DONE" -ne 0 ]; do
+    HTTP_CODE=$(curl -f \
+         --cert "${JACK_HOME}/client.pem" \
+         --cacert "${JACK_HOME}/server.pem" \
+         --output >(cat >/dev/null) \
+         --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
+         -X GET \
+         -H "Accept: text/plain;charset=$CURRENT_CHARSET" \
+         --noproxy ${SERVER_HOST} \
+         https://${SERVER_HOST}:$SERVER_PORT_ADMIN/server \
+         )
+    CURL_CODE=$?
+    if [ $CURL_CODE -eq 7 ] || [ $CURL_CODE -eq 35 ] || [ $CURL_CODE -eq 58 ] || [ $CURL_CODE -eq 60 ] || [ $CURL_CODE -eq 77 ]; then
+      if [ $RETRY_CONNECT -eq 0 ]; then
+        echo "Jack server failed to (re)start, see Jack server log" >&2
+        abort
+      else
+        let RETRY_CONNECT=RETRY_CONNECT-1
+        sleep 1;
+      fi
+    else
+      # A connection was opened, no need to know if it went well
+      DONE=0;
+    fi
+  done
+}
+
+#
+# $1: program name
+#
+listProgramVersion () {
+  RETRY_SESSION=3
+  DONE=1
+  while [ "$DONE" -ne 0 ]; do
+    exec 3>&1
+    HTTP_CODE=$(curl -f \
+         --cert "${JACK_HOME}/client.pem" \
+         --cacert "${JACK_HOME}/server.pem" \
+         --output >(tr -d '\015' >&3) \
+         --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
+         -X GET \
+         -H "Accept: text/plain;charset=$CURRENT_CHARSET" \
+         --noproxy ${SERVER_HOST} \
+         https://${SERVER_HOST}:$SERVER_PORT_ADMIN/$1 \
+         )
+    handleHttpErrors $? $HTTP_CODE
+    DONE=$?
+    exec 3>&-
+  done
+}
 
 #
 # Decoding argument
 #
-
-if [ $# -ne 1 ]
+if [ $# -eq 0 ]
 then
-        echo "Usage : $0 [ start-server | stop-server | kill-server | list-server | server-log | server-stat ]"
-        exit 255
+  usage
+  abort
 fi
-
-case $1 in
-  stop-server)
-    echo "Stopping background server"
-    CMD="stop" ;;
-  server-stat)
-    echo "Getting statistic from background server"
-    CMD="stat" ;;
-  server-log)
-    echo "Log location of background server:"
-    echo $SERVER_LOG
-    exit 0 ;;
-  kill-server)
-    echo "Killing background server"
-    kill $(ps aux | grep JackSimpleServer | grep -v grep | awk '{print $2}') 2>/dev/null
-    if [ $? -ne 0 ]; then
-      echo "ERROR: No Jack server to kill" >&2
-      exit 2
-    else
-      exit 0 
-    fi ;;
-  list-server)
-    ps aux | grep JackSimpleServer | grep -v grep
-    exit $? ;;
-  start-server)
-    SERVER_PRG="$JACK_VM_COMMAND -cp $JACK_JAR com.android.jack.server.JackSimpleServer"
-    echo "Launching Jack server" $SERVER_PRG
-    $SERVER_PRG $SERVER_PORT_SERVICE $SERVER_PORT_ADMIN $SERVER_COUNT $SERVER_NB_COMPILE $SERVER_TIMEOUT >>$SERVER_LOG 2>&1 &
-    exit 0 ;;
-  *)
-    echo "Usage : $0 [ start-server | stop-server | kill-server | list-server | server-log | server-stat ]"
-    exit 255 ;;
-esac
-
-#
-# Send command
-#
 
 set +o errexit
 
-# Try to cleanup if interrupted
-# Cleanup
-JACK_EXIT="$SERVER_DIR/admin-$$"
-trap 'rm -f "$JACK_EXIT" 2>/dev/null;' EXIT
+FORCE_INSTALLATION=false
+case $1 in
+  force-update)
+    FORCE_INSTALLATION=true
+    COMMAND=update;;
+  *)
+    COMMAND=$1;;
+esac
 
-RETRY_SESSION=3
-DELAY_CONNECT=3
-
-
-# Send command to Jack server
-DATE_CONNECT=$(date +%s)
-while true; do
-  HTTP_CODE=$(curl --fail --silent --output $JACK_EXIT --write-out %{http_code} --connect-timeout 5 --no-proxy 127.0.0.1:$SERVER_PORT_ADMIN http://127.0.0.1:$SERVER_PORT_ADMIN/$CMD)
-  CURL_CODE=$?
-  if [ $CURL_CODE -eq 0 ]; then
-    # No problem, let's go
-    break;
-  elif [ $CURL_CODE -eq 7 ]; then
-    # Failed to connect
-    if [ $(date +%s) -ge $DATE_CONNECT ]; then
-        echo "ERROR: No Jack server running"
-        exit 255
-    else
-      sleep 0.2 2>/dev/null
+case $COMMAND in
+  install-server)
+    if [ $# -ne 3 ]; then
+      usage
+      abort
     fi
-    # Trying with a new connection, let's retry session 3 times max
+    if [ ! -r "$2" ]; then
+      echo "Jack server launcher jar \"$2\" is not readable" >&2
+      abort
+    fi
+     if [ ! -r "$3" ]; then
+      echo "Jack server jar \"$3\" is not readable" >&2
+      abort
+    fi
+
+    checkCurlVersion
+
+    if [ ! -d "$JACK_HOME" ]; then
+      echo Installing jack server in \"$JACK_HOME\"
+      mkdir -p "$JACK_HOME"
+      cp $2 "$LAUNCHER_JAR"
+      cp $3 "$JACK_HOME/server-1.jar"
+      mkdir "$JACK_LOGS_DIR"
+      keytool -genkeypair -validity 3650 -alias server -keyalg RSA -keysize 2048 -keypass Jack-Server -storepass Jack-Server -dname "CN=$SERVER_HOST" -keystore "$JACK_HOME/server.jks"
+      keytool -genkeypair -validity 3650 -alias client -keyalg RSA -keysize 2048 -keypass Jack-Server -storepass Jack-Server -dname "CN=$(id -un)@$(uname -n)" -keystore "$JACK_HOME/client.jks"
+    else
+      echo "Jack server already installed in \"$JACK_HOME\"" >&2
+      abort
+    fi
+    exit 0 ;;
+
+
+  uninstall-server)
+    if [ ! -d "$JACK_HOME" ]; then
+      echo "Jack server in \"$JACK_HOME\" not found" >&2
+      abort
+    else
+      echo "Removing jack server from \"$JACK_HOME\""
+      rm -rf "$JACK_HOME"
+    fi
+    exit 0 ;;
+
+
+  list)
+    if [ $# -ne 2 ]
+    then
+      usage
+      abort
+    fi
+
+    listProgramVersion $2 ;;
+
+
+  update)
+    if [ $# -lt 3 ]; then
+      usage
+      abort
+    fi
+
+    if [ $# -gt 4 ]; then
+      usage
+      abort
+    fi
+
+    if [ ! -r "$3" ]; then
+      echo "Failed to update $2 of Jack server: \"$3\" is not readable" >&2
+      abort
+    fi
+
+    checkCurlVersion
+
+    if [ $FORCE_INSTALLATION = true ]; then
+      updateProgram $2 $3
+    else
+      if [ $# -eq 4 ]; then
+        RETRY_SESSION=3
+        DONE=1
+        while [ "$DONE" -ne 0 ]; do
+          HTTP_CODE=$(curl -f \
+               --cert "${JACK_HOME}/client.pem" \
+               --cacert "${JACK_HOME}/server.pem" \
+               --output >(cat >/dev/null) \
+               --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
+               -X HEAD \
+               --data "$4" \
+               -H "Content-Type:application/vnd.jack.select-exact;version=1" \
+               --noproxy ${SERVER_HOST} \
+               https://${SERVER_HOST}:$SERVER_PORT_ADMIN/$2 \
+               )
+          CURL_CODE=$?
+          if [ $CURL_CODE -eq 22 ]; then
+            if [ $HTTP_CODE -eq 404 ]; then
+              # version not found, proceed to installation
+              updateProgram $2 $3
+              exit 0
+            fi
+          fi
+          handleHttpErrors $CURL_CODE $HTTP_CODE
+          DONE=$?
+        done
+      else
+        # No version provided, proceed directly without testing
+        updateProgram $2 $3
+      fi
+    fi
+    exit 0;;
+
+
+  stop-server)
+    echo "Stopping background server"
+
     RETRY_SESSION=3
-  elif  [ $CURL_CODE -eq 22 ]; then
-    # Http code not OK, let's decode and abort
-    if [ $HTTP_CODE -eq 401 ]; then
-      # 401: Unauthorized
-      echo "ERROR: Security problem, see Jack server log" >&2
-      exit 255
-    elif [ $HTTP_CODE -eq 400 ]; then
-      # 400: Bad request
-      echo "ERROR: Bad request, see Jack server log" >&2
-      exit 255
+    DONE=1
+    while [ "$DONE" -ne 0 ]; do
+      HTTP_CODE=$(curl -f \
+           --cert "${JACK_HOME}/client.pem" \
+           --cacert "${JACK_HOME}/server.pem" \
+           --output >(cat >/dev/null) \
+           --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
+           -X POST \
+           --noproxy ${SERVER_HOST} \
+           https://${SERVER_HOST}:$SERVER_PORT_ADMIN/server/stop \
+           )
+      handleHttpErrors $? $HTTP_CODE
+      DONE=$?
+    done ;;
+
+
+  server-stat)
+    echo "Getting statistic from background server"
+
+    RETRY_SESSION=3
+    DONE=1
+    while [ "$DONE" -ne 0 ]; do
+      exec 3>&1
+      HTTP_CODE=$(curl -f \
+           --cert "${JACK_HOME}/client.pem" \
+           --cacert "${JACK_HOME}/server.pem" \
+           --output >(tr -d '\015' >&3) \
+           --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
+           -X GET \
+           -H "Accept: text/plain;charset=$CURRENT_CHARSET" \
+           --noproxy ${SERVER_HOST} \
+           https://${SERVER_HOST}:$SERVER_PORT_ADMIN/stat \
+           )
+      handleHttpErrors $? $HTTP_CODE
+      DONE=$?
+      exec 3>&-
+    done ;;
+
+
+  server-log)
+    RETRY_SESSION=3
+    DONE=1
+    while [ "$DONE" -ne 0 ]; do
+      exec 3>&1
+      HTTP_CODE=$(curl -f \
+           --cert "${JACK_HOME}/client.pem" \
+           --cacert "${JACK_HOME}/server.pem" \
+           --output >(tr -d '\015' >&3) \
+           --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
+           -X GET \
+           -H "Accept: text/plain;charset=$CURRENT_CHARSET" \
+          --noproxy ${SERVER_HOST} \
+           https://${SERVER_HOST}:$SERVER_PORT_ADMIN/launcher/log \
+           )
+      handleHttpErrors $? $HTTP_CODE
+      DONE=$?
+      exec 3>&-
+    done ;;
+
+
+  kill-server)
+    echo "Killing background server"
+    kill $(ps aux | grep $LAUNCHER_NAME | grep -v grep | awk '{print $2}') 2>/dev/null
+    if [ $? -ne 0 ]; then
+      echo "No Jack server to kill" >&2
+      exit 2
     else
-      # Other
-      echo "ERROR: Internal unknown error ($HTTP_CODE), try other ports in ~/.jack, or see Jack server log" >&2
-      exit 255
-    fi
-  else
-    # In case of partial, timeout, empty respond, network error, let's retry
-    if [ $RETRY_SESSION -eq 0 ]; then
-      echo "ERROR: Communication error with Jack server ($CURL_CODE)" >&2
-      exit 255
+      exit 0
+    fi ;;
+
+
+  list-server)
+    ps aux | grep $LAUNCHER_NAME | grep -v grep
+    exit $? ;;
+
+
+  start-server)
+    isServerRunning
+    RUNNING=$?
+    if [ "$RUNNING" = 0 ]; then
+      echo "Server is already running"
     else
-      let RETRY_SESSION=RETRY_SESSION-1
+      JACK_SERVER_COMMAND="java -Djava.io.tmpdir=$TMPDIR $JACK_SERVER_VM_ARGUMENTS -cp $LAUNCHER_JAR $LAUNCHER_NAME"
+      echo "Launching Jack server" $JACK_SERVER_COMMAND
+      (
+        trap "" SIGHUP
+        for i in $(seq 3 255); do
+          eval exec "$i"'>&-'
+        done
+        cd "$JACK_HOME"
+        umask $BASE_UMASK
+        exec $JACK_SERVER_COMMAND
+        abort
+      ) >"$JACK_OUT_ERR" 2>&1 &
     fi
-  fi
-done
+
+    waitServerStarted
+    exit 0 ;;
+
+
+  server-log-level)
+    if [ $# -eq 4 ]
+    then
+      LIMIT=$3
+      COUNT=$4
+    elif [ $# -eq 2 ]
+    then
+      COUNT=2
+      if [ \( "$2" = "ERROR" \) -o \( "$2" = "WARNING" \) ]
+      then
+        LIMIT=1048576
+      else
+        LIMIT=10485760
+      fi
+    else
+      usage
+      abort
+    fi
+
+    echo "Setting logging parameters of background server"
+
+    RETRY_SESSION=3
+    DONE=1
+    while [ "$DONE" -ne 0 ]; do
+      HTTP_CODE=$(curl --fail \
+           --cert "${JACK_HOME}/client.pem" \
+           --cacert "${JACK_HOME}/server.pem" \
+           --output >(cat >/dev/null) \
+           --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
+           --request PUT \
+           --form "level=$2;type=text/plain;charset=$CURRENT_CHARSET" \
+           --form "limit=$LIMIT;type=text/plain;charset=$CURRENT_CHARSET" \
+           --form "count=$COUNT;type=text/plain;charset=$CURRENT_CHARSET" \
+           --noproxy ${SERVER_HOST} \
+           https://${SERVER_HOST}:$SERVER_PORT_ADMIN/launcher/log/level \
+           )
+      handleHttpErrors $? $HTTP_CODE
+      DONE=$?
+    done ;;
+
+
+  server-gc)
+    echo "Requesting a garbage collection to the background server"
+
+    RETRY_SESSION=3
+    DONE=1
+    while [ "$DONE" -ne 0 ]; do
+      HTTP_CODE=$(curl -f \
+           --cert "${JACK_HOME}/client.pem" \
+           --cacert "${JACK_HOME}/server.pem" \
+           --output >(cat >/dev/null) \
+           --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
+           -X POST \
+           --noproxy ${SERVER_HOST} \
+           https://${SERVER_HOST}:$SERVER_PORT_ADMIN/gc \
+           )
+      handleHttpErrors $? $HTTP_CODE
+      DONE=$?
+    done ;;
+
+
+#
+# Should be run when server is off. Allows to clean files that could be forgotten on disk in case of
+# server VM crash after an update.
+#
+  cleanup-server)
+    shopt -s nullglob
+    for file in $JACK_HOME/jack/*.deleted; do
+      rm "${file%.deleted}"
+      rm "$file"
+    done
+    exit 0 ;;
+
+
+  *)
+    usage
+    abort ;;
+esac
+
 
 # Exit
-if [ -r $JACK_EXIT ]; then
-  cat <$JACK_EXIT 2>/dev/null
-fi
 
 exit 0
